sudo: required

language: scala

scala: 2.11.11

install:
  - sudo pip install cloudsmith-cli
  
script:
  - sbt clean test package
  
after_success:
  - echo "Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
  - export ARTIFACT=/
  - cloudsmith push maven byrde/libraries $ARTIFACT.jar
