sudo: required

# Define the following to reuse:
# - CLOUDSMITH_API_KEY
# - NAME
# - ORGANIZATION
# - MAJOR_VERSION

# Defacto version and lang used in most Byrde projects.
language: scala
jdk: oraclejdk8
scala:
- 2.12.7

# Clean tracked binaries, run unit tests, and package artifact.
script:
- sbt clean test

# Cached dependencies cleanup.
before_cache:
# Cleanup the cached directories to avoid unnecessary cache updates
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete

# Cache dependencies.
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt

# Dependencies for publishing
before_deploy:
- pyenv global 2.7
- pip install --upgrade pip
- pip install --upgrade setuptools
- pip install --upgrade wheel
- pip install cloudsmith-cli
- pip install twine

# On script complete, publish artifact to cloudsmith.
deploy:
  provider: script
  skip_cleanup: true
  script: "./scripts/deploy.sh"

branches:
  only:
  - master
