sudo: required

# Defacto version and lang used in most Byrde projects.
language: scala
scala: $SCALA_VER

# Python 3.6 as dependency for cloudsmith installation.
addons:
  apt:
    sources:
      - deadsnakes # source required so it finds the package definition below
    packages:
      - python3.6

# Install cloudsmit cli, required for publishing artifact.
install:
  - echo "alias python=python3" >> ~/.bashrc
  - echo "alias python=python3" >> ~/.bash_profile
  - echo "alias python=python3" >> ~/.bash_aliases
  - |
    if [ ${TRAVIS_BRANCH} == 'master' ]; then
      python -V;
      sudo pip install pyOpenSSL ndg-httpsclient pyasn1;
      sudo pip install cloudsmith-cli; 
    fi

# Clean tracked binaries, run unit tests, and package artifact.
script:
  - sbt -Dname=${PROJECT_NAME} -Dversion=${PROJECT_VERSION} -DscalaVersion=${SCALA_VERSION} clean test
  - |
    if [ ${TRAVIS_BRANCH} == 'master' ]; then 
      sbt -Dname=${PROJECT_NAME} -Dversion=${PROJECT_VERSION} -DscalaVersion=${SCALA_VERSION} package; 
    fi

# Cached dependencies cleanup.
before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

# Cache dependencies.
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

# On script complete, publish artifact to cloudsmith.
after_success:
  - |
    if [ ${TRAVIS_BRANCH} == 'master' ]; then 
      cd ${COMPILE_DIRECTORY};
      cloudsmith push maven byrde/libraries ${PROJECT_NAME}_2.11-${PROJECT_VERSION}.jar; 
    fi
