sudo: required

# Define the following to reuse:
# - CLOUDSMITH_API_KEY
# - NAME
# - ORGANIZATION
# - MINOR_VERSION
# - MAJOR_VERSION

# Defacto version and lang used in most Byrde projects.
language: scala
jdk: oraclejdk9
scala:
- 2.12.8

# Install credentials
before_script:
- |
  cat <<EOF >/home/travis/.sbt/.credentials
  realm=Cloudsmith API
  host=maven.cloudsmith.io
  user=token
  password=${CLOUDSMITH_API_KEY}
  EOF
- cd $TRAVIS_BUILD_DIR

# Clean tracked binaries, run unit tests, and package artifact.
# script:
# - sbt -Dversion="${MAJOR_VERSION}.${MINOR_VERSION}.$TRAVIS_BUILD_NUMBER" 'set credentials += Credentials("Cloudsmith API", "maven.cloudsmith.io", "token", "${CLOUDSMITH_API_KEY}")' clean test

# Cached dependencies cleanup.
before_cache:
# Cleanup the cached directories to avoid unnecessary cache updates
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete

# Cache dependencies.
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt

# Dependencies for publishing
before_deploy:
- pyenv global 2.7
- pip install --upgrade pip
- pip install --upgrade setuptools
- pip install --upgrade wheel
- pip install cloudsmith-cli
- pip install twine

# On script complete, publish artifact to cloudsmith.
deploy:
  provider: script
  skip_cleanup: true
  script: "./deploy.sh"

branches:
  only:
  - master
