sudo: required

# Defacto version and lang used in most Byrde projects.
language: scala
scala: $SCALA_VER

# Install cloudsmit cli, required for publishing artifact.
install:
  - |
    if [ ${TRAVIS_BRANCH} == 'master' ]; then
      sudo apt-get install python3-pip;
      sudo python3 -m pip install --upgrade cloudsmith-cli;
    fi

# Clean tracked binaries, run unit tests, and package artifact.
script:
  - sbt -Dname=${PROJECT_NAME} -Dversion=${PROJECT_VERSION} -DscalaVersion=${SCALA_VERSION} clean test
  - |
    if [ ${TRAVIS_BRANCH} == 'master' ]; then 
      sbt -Dname=${PROJECT_NAME} -Dversion=${PROJECT_VERSION} -DscalaVersion=${SCALA_VERSION} package; 
    fi

# Cached dependencies cleanup.
before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

# Cache dependencies.
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

# On script complete, publish artifact to cloudsmith.
after_success:
  - |
    if [ ${TRAVIS_BRANCH} == 'master' ]; then 
      cd ${COMPILE_DIRECTORY};
      cloudsmith push maven byrde/libraries ${PROJECT_NAME}_2.11-${PROJECT_VERSION}.jar; 
    fi
