sudo: required

# Defacto version and lang used in most Byrde projects.
language: scala
scala: 2.${SCALA_MAJOR_VERSION}.${SCALA_MINOR_VERSION}

# Install cloudsmit cli, required for publishing artifact.
install:
  - |
    if [ ${TRAVIS_BRANCH} == 'master' ]; then
      # Install cloudsmith.
      sudo apt-get install python3-pip;
      sudo python3 -m pip install --upgrade cloudsmith-cli;

      # Configure cloudsmith.
      sudo mkdir -p ~/.config/cloudsmith/;
      sudo touch  ~/.config/cloudsmith/config.ini;
      sudo chmod 777  ~/.config/cloudsmith/config.ini;
      sudo echo "[default] api_key=${CLOUDSMITH_API_KEY}" >> ~/.config/cloudsmith/config.ini;
    fi

# Clean tracked binaries, run unit tests, and package artifact.
script:
  - sbt -Dname=${PROJECT_NAME} -Dversion=${PROJECT_VERSION}.${TRAVIS_BUILD_NUMBER} -DscalaVersion=2.${SCALA_MAJOR_VERSION}.${SCALA_MINOR_VERSION} clean test
  - |
    if [ ${TRAVIS_BRANCH} == 'master' ]; then 
      sbt -Dname=${PROJECT_NAME} -Dversion=${PROJECT_VERSION}.${TRAVIS_BUILD_NUMBER} -DscalaVersion=2.${SCALA_MAJOR_VERSION}.${SCALA_MINOR_VERSION} -DmavenGroupId=${MAVEN_GROUP_ID} package make-pom; 
    fi

# Cached dependencies cleanup.
before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

# Cache dependencies.
cache:
  directories:
    - $HOME/.m2
    - $HOME/.ivy2
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION
    - $HOME/.sbt/launchers

# On script complete, publish artifact to cloudsmith.
after_success:
  - |
    if [ ${TRAVIS_BRANCH} == 'master' ]; then 
      cd ${COMPILE_DIRECTORY}/scala-2.${SCALA_MAJOR_VERSION};
      cloudsmith push maven byrde/libraries ${PROJECT_NAME}_2.${SCALA_MAJOR_VERSION}-${PROJECT_VERSION}.${TRAVIS_BUILD_NUMBER}.jar --pom-file=${PROJECT_NAME}_2.${SCALA_MAJOR_VERSION}-${PROJECT_VERSION}.${TRAVIS_BUILD_NUMBER}.pom; 
    fi

# Configure notifications
notifications:
  email:
    recipients:
      - ${ADMINISTRATIVE_EMAIL}
    on_success: never
    on_failure: always
