name: Commons CI/CD
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAJOR_VERSION: "2"
      MINOR_VERSION: "0"
      GITHUB_NUMBER: ${{ github.run_number }}
      GITHUB_ACTOR:  ${{ github.actor }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
#     - name: Test
#       run: sbt clean test
    - name: Create Credentials Directory
      run: mkdir -p ${HOME}/.sbt
    - name: Prepare Credentials
      run: |
        cat <<EOF >${HOME}/.sbt/.credentials
        realm=GitHubPackages
        host=maven.pkg.github.com
        user=${GITHUB_ACTOR}
        password=${GITHUB_TOKEN}
        EOF
    - name: Publish
      run: sbt -Dversion="${MAJOR_VERSION}.${MINOR_VERSION}.${GITHUB_NUMBER}" publish
