name: Commons CI/CD
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAJOR_VERSION: "2"
      MINOR_VERSION: "0"
      GITHUB_NUMBER: ${{ github.run_number }}
      MAVEN_REALM: "GitHub Package Registry"
      MAVEN_HOST: "maven.pkg.github.com"
      MAVEN_USER: ${{ github.actor }}
      MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
#     - name: Test
#       run: sbt clean test
    - name: Publish
      run: sbt -Dversion="${MAJOR_VERSION}.${MINOR_VERSION}.${GITHUB_NUMBER}" publish
