name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  main:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Test
        uses: 'uses: lokkju/github-action-sbt@master'